version: '3'

services:
  linehaul:
    build: .
    command: python -m linehaul --log-level debug server --port 8512 --token insecuretoken --credentials-file /opt/linehaul/src/dev/GCP.json <bigquery table>
    environment:
      - LINEHAUL_DATADOG_HOST=notdatadog
    volumes:
      - .:/opt/linehaul/src:z
    ports:
      - "8512:8512"
    links:
      - notdatadog

  notdatadog:
    build:
      context: .
    command: python /opt/linehaul/src/dev/notdatadog.py 0.0.0.0:8125
    ports:
      - "8125:8125/udp"
    volumes:
      - ./dev/notdatadog.py:/opt/linehaul/src/dev/notdatadog.py
